"""
FastAPI application — the AI Document Reader API.

Endpoints:
  POST /upload            Upload a PDF, extract its text, store it.
  POST /ask               Ask a question about a stored document.
  GET  /history/{doc_id}  Get the chat history for a document.
  GET  /health            Simple liveness check.

Interactive API docs are auto-generated at /docs (Swagger) and /redoc.
"""
import logging
from contextlib import asynccontextmanager
from fastapi import FastAPI, UploadFile, File, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel

import database as db
from services import pdf_service, llm_service, storage_service

# --- Logging setup (requirement 8: meaningful logging) ---
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s  %(levelname)s  %(name)s  %(message)s",
)
logger = logging.getLogger(__name__)


@asynccontextmanager
async def lifespan(app: FastAPI):
    """Run once on startup: ensure DB tables and the storage bucket exist."""
    db.init_db()
    storage_service.ensure_bucket()
    yield
    # (nothing to clean up on shutdown)


app = FastAPI(
    title="AI-Powered Document Reader",
    description="Upload PDFs, extract text, and ask questions answered by Gemini.",
    version="1.0.0",
    lifespan=lifespan,
)

# Allow the React dev server to call this API during development.
app.add_middleware(
    CORSMiddleware,
    allow_origins=[
        "http://localhost:5173",
        "http://localhost:3000",
        "https://pai-dr.vercel.app/",
    ],
    allow_methods=["*"],
    allow_headers=["*"],
)


# --- Request/response models (these shape the Swagger docs) ---
class AskRequest(BaseModel):
    document_id: int
    question: str


class UploadResponse(BaseModel):
    document_id: int
    filename: str
    method: str          # "text" or "ocr"
    text: str
    char_count: int


class AskResponse(BaseModel):
    answer: str


# --- Endpoints ---
@app.get("/health")
def health() -> dict:
    """Liveness check."""
    return {"status": "ok"}


@app.post("/upload", response_model=UploadResponse)
async def upload(file: UploadFile = File(...)) -> UploadResponse:
    """
    Upload a PDF. Extracts text (with OCR fallback for scanned PDFs),
    stores it, and returns the text plus a document ID for asking questions.
    """
    if not file.filename.lower().endswith(".pdf"):
        raise HTTPException(status_code=400, detail="Only PDF files are accepted.")

    file_bytes = await file.read()
    if not file_bytes:
        raise HTTPException(status_code=400, detail="The uploaded file is empty.")

    try:
        text, method = pdf_service.extract_text(file_bytes)
    except pdf_service.PDFExtractionError as e:
        # Bad or unreadable PDF — a client error, not a server crash.
        logger.warning("Extraction failed for %s: %s", file.filename, e)
        raise HTTPException(status_code=422, detail=str(e))

    # Store the original PDF in Supabase Storage. If storage fails, we still
    # keep the extracted text — the file path is nice-to-have, not critical.
    storage_path = None
    try:
        storage_path = storage_service.upload_pdf(file.filename, file_bytes)
    except Exception as e:
        logger.warning("Could not store PDF in Supabase Storage: %s", e)

    doc_id = db.save_document(file.filename, text, method, storage_path)
    logger.info("Stored document %d (%s) via %s.", doc_id, file.filename, method)

    return UploadResponse(
        document_id=doc_id,
        filename=file.filename,
        method=method,
        text=text,
        char_count=len(text),
    )


@app.post("/ask", response_model=AskResponse)
def ask(req: AskRequest) -> AskResponse:
    """
    Ask a question about a previously uploaded document.
    The answer is generated by Gemini using the document text and
    the recent chat history for context.
    """
    if not req.question.strip():
        raise HTTPException(status_code=400, detail="Question cannot be empty.")

    doc = db.get_document(req.document_id)
    if doc is None:
        raise HTTPException(status_code=404, detail="Document not found.")

    history = db.get_history(req.document_id)

    try:
        answer = llm_service.answer_question(doc["text"], req.question, history)
    except llm_service.DocumentTooLargeError as e:
        raise HTTPException(status_code=413, detail=str(e))
    except llm_service.LLMError as e:
        # The AI service failed — surface a clean 502, not a crash.
        raise HTTPException(status_code=502, detail=str(e))

    db.save_message(req.document_id, req.question, answer)
    return AskResponse(answer=answer)


@app.get("/history/{document_id}")
def history(document_id: int) -> dict:
    """Return the full chat history for a document."""
    doc = db.get_document(document_id)
    if doc is None:
        raise HTTPException(status_code=404, detail="Document not found.")

    return {
        "document_id": document_id,
        "filename": doc["filename"],
        "messages": db.get_history(document_id),
    }